(function(){"use strict";const initFormValidation=()=>{document.querySelectorAll(".preventNumbers").forEach((input)=>{input.addEventListener("input",function(){this.value=this.value.replace(/[0-9]/g,"")})});const contactForm=document.getElementById("contactForm");if(!contactForm)return;const name=document.getElementById("nameInput");const email=document.getElementById("emailInput");const phone=document.getElementById("phoneInput");const message=document.getElementById("message");const nameError=document.getElementById("nameError");const emailError=document.getElementById("emailError");const phoneError=document.getElementById("validMsg");const messageError=document.getElementById("messageError");const actualPhone=document.getElementById("actualPhone");let iti;if(phone&&window.intlTelInput){iti=window.intlTelInput(phone,{initialCountry:"sa",preferredCountries:["eg","sa","ae","kw","qa","jo"],separateDialCode:!0,loadUtils:()=>import("https://cdn.jsdelivr.net/npm/intl-tel-input@26.0.6/build/js/utils.js"),})}
const validateName=()=>{if(!name)return!0;const value=name.value.trim();const hasNumber=/\d/.test(value);const smalls=nameError?nameError.querySelectorAll("small"):[];smalls[0]?.classList.add("hidden");smalls[1]?.classList.add("hidden");if(value.length<3){smalls[0]?.classList.remove("hidden");return!1}
if(hasNumber){smalls[1]?.classList.remove("hidden");return!1}
return!0};const validateEmail=()=>{if(!email)return!0;const value=email.value.trim();const regex=/^[^ ]+@[^ ]+\.[a-z]{2,3}$/i;if(!regex.test(value)){emailError?.classList.remove("hidden");return!1}
emailError?.classList.add("hidden");return!0};const validatePhone=()=>{if(!phone)return!0;const value=phone.value.trim();phoneError?.classList.add("hidden");if(!value){if(phoneError){phoneError.textContent="Phone number is required.";phoneError.classList.remove("hidden")}
return!1}
if(iti&&!iti.isValidNumber()){if(phoneError){phoneError.textContent="Invalid phone number.";phoneError.classList.remove("hidden")}
return!1}
return!0};const validateMessage=()=>{if(!message)return!0;if(message.value.trim().length<10){messageError?.classList.remove("hidden");return!1}
messageError?.classList.add("hidden");return!0};if(name)name.addEventListener("input",validateName);if(email)email.addEventListener("input",validateEmail);if(phone){phone.addEventListener("input",validatePhone);phone.addEventListener("blur",validatePhone)}
if(message)message.addEventListener("input",validateMessage);contactForm.addEventListener("submit",function(e){const isNameValid=validateName();const isEmailValid=validateEmail();const isPhoneValid=validatePhone();const valid=isNameValid&&isEmailValid&&isPhoneValid&&isMessageValid;if(valid){if(iti){const countryData=iti.getSelectedCountryData();const phoneValue=phone.value.trim();const dialCode=countryData?.dialCode||"20";const phoneWithCode=`+${dialCode}${phoneValue}`;if(actualPhone)actualPhone.value=phoneWithCode}
alert("Form submitted successfully!")}else{e.preventDefault()}})};document.addEventListener("DOMContentLoaded",()=>{initFormValidation()})})()